# Go cross compiler (xgo): Go 1.12.x
# Copyright (c) 2019 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM goreng/xgo:1.12.9

LABEL MAINTAINER Péter Szilágyi <peterke@gmail.com>
